name: MGSurvE
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - aiosqlite
  - alabaster
  - appdirs
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - bleach
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bs4
  - bzip2
  - c-ares
  - ca-certificates
  - cartopy
  - cffi
  - colorama
  - comm
  - contourpy
  - cryptography
  - cycler
  - deap
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - et_xmlfile
  - exceptiongroup
  - executing
  - flit-core
  - fonttools
  - freetype
  - geos
  - idna
  - imagesize
  - importlib-metadata
  - importlib_resources
  - ipython_genutils
  - jedi
  - jinja2
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_terminals
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libjpeg-turbo
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libsodium
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libzlib
  - llvm-openmp
  - matplotlib-inline
  - munkres
  - nbclassic
  - nbconvert-core
  - nbconvert-pandoc
  - ncurses
  - nest-asyncio
  - notebook
  - notebook-shim
  - numexpr
  - numpy
  - openjpeg
  - openpyxl
  - openssl
  - overrides
  - pandoc
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - pooch
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyopenssl
  - pyparsing
  - pyproj
  - pyrsistent
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python_abi
  - pyyaml
  - readline
  - rfc3339-validator
  - rfc3986-validator
  - send2trash
  - setuptools
  - shapely
  - six
  - sniffio
  - snowballstemmer
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - tomli
  - traitlets
  - typing-extensions
  - typing_extensions
  - typing_utils
  - unicodedata2
  - wcwidth
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - y-py
  - yaml
  - ypy-websocket
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - anyio
      - arrow
      - cattrs
      - certifi
      - chardet
      - charset-normalizer
      - click
      - click-plugins
      - cligj
      - compress-pickle
      - dill
      - docutils
      - esbonio
      - fastjsonschema
      - fiona
      - fqdn
      - geojson
      - geopandas
      - haversine
      - ipykernel
      - ipython
      - ipython-genutils
      - ipywidgets
      - isoduration
      - jaraco-classes
      - joblib
      - jsonpointer
      - jupyter
      - jupyter-client
      - jupyter-console
      - jupyter-core
      - jupyter-server
      - jupyterlab-widgets
      - keyring
      - libpysal
      - lsprotocol
      - lxml
      - markdown-it-py
      - markupsafe
      - matplotlib
      - mdurl
      - mgsurve
      - mistune
      - more-itertools
      - mpmath
      - munch
      - nbclient
      - nbconvert
      - nbformat
      - networkx
      - osmpythontools
      - packaging
      - pandas
      - pkginfo
      - platformdirs
      - pointpats
      - prometheus-client
      - pygls
      - pyspellchecker
      - pytz
      - pyzmq
      - qtconsole
      - qtpy
      - readme-renderer
      - requests
      - requests-toolbelt
      - rfc3986
      - rich
      - scikit-learn
      - scipy
      - soupsieve
      - sphinx
      - sphinx-rtd-theme
      - sphinxcontrib-jquery
      - sympy
      - termcolor
      - threadpoolctl
      - tornado
      - twine
      - typeguard
      - tzdata
      - ujson
      - uri-template
      - urllib3
      - vincenty
      - webcolors
      - webencodings
      - websocket-client
      - widgetsnbextension
      - xarray
